### ISSUE TITLE
Bytecord API Base

### ISSUE THREAD

**Issue by gabrielrosa2004** [bytecord/bytecord#3]
# Introduction
It's a HTTP Client Process to make Discord API requests.

# Task List
- [x] Process Request URL
- [x] Process Request Headers
- [x] Process Response Body
